### PR TITLE
review & consider pulling

### PR DESCRIPTION
**Pull request by chris-piekarski**
Hi Kami, I've done some work on the python-face-client. I removed the multipart module (wasn't working for my pictures) that came bundled and replaced it with poster. I also reworked and reorganized the FaceClient API methods. Take a look and if you like it consider pulling it.

Let me know if you have any questions,
Chris

### CODE REVIEW

**Comment by Kami** [comment]
Hi

I like some of the changes, but not all of them. 

What I like:
- Logging requests and responses
- I'm not sure why the current multipart module didn't work with your pictures. In any case, I'm OK with replacing it with the poster module. In this case requirements in `setup.py` also need to be updated

What I don't like:
- Why did you change method names to be camelCase? PEP8 says the method names should be underscore_separated. Twisted does this for historical reasons and nobody likes it. In this case, this change adds no value, but it just breaks the API for no good reason.
- Using lamba.

**Comment by chris-piekarski** [comment]
> camelCase

As with any coding standard its just a matter of opinion. Despite PEP8 I personally dislike _separated APIs. I only like to add a '_'  when distinguish from private/public methods. PEP8 also suggests spaces over tabs, which with an indent based language like Python never made any sense to me ;-)

> lambda

What do you have against lambda? Its one of Python's best features :-)

Don't pull if you're not happy, I just wanted to notify you of the option. I was more interested in getting feedback on the rework of the FaceClient class which is now broken down into more finite operations and is easier to maintain in my opinion. When face.com updates its API I can maintain this fork separately, no biggy.

**Comment by Kami** [comment]
Yes you are right, naming / style is a matter of opinion, but luckily in Python we have semi-formal PEP8 so we don't need to argue about it.

Another thing to keep in mind when you work on the project / file you didn't create it so follow the original author style.

I would be OK with merging this branch under the following conditions:
- Style changes get reverted
- poster gets added as a requirement in setup.py
- log level should be set to error / critical by default
- library name change gets reverted

off-topic (spaces vs tabs):

In this case, problem isn't really using spaces or tabs, but mixing them which can't be done safely.

**Comment by chris-piekarski** [comment]
Changes on my fork under branch PEP8. Unless there is something majorly wrong that's all the work I'm going to put in for a downward fork merge.

> Style changes get reverted

Scores a 9.8/10 on the PEP8 Linter

> poster gets added as a requirement in setup.py

Done.

> log level should be set to error / critical by default

Done.

> library name change gets reverted

name was reverted to be longer

> follow the original author style

You're right, I wasn't concerned initially about making it backward compatible. I didn't see too many recent clones and not too many followers/forkers so I assumed it was a pretty new project and therefor not yet stuck on an API definition. I hope you find my changes useful.

Let me know if you have any issues,
Chris

**Comment by Kami** [comment]
Can you please open a pull request?

It makes it easier to go over changes.

**Pull request closed without merging**
